apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mark42
  template:
    metadata:
      labels:
        app: mark42
    spec:
      containers:
      - name: mark42
        image: nginx:alpine
        resources: {}
        ports:
        - containerPort: 80
