apiVersion: v1
kind: Namespace
metadata:
  name: colors
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmobile-deployment
  namespace: colors
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: redmobile-webserver
        image: nginx:alpine
        resources: {}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluemobile-deployment
  namespace: colors
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: bluemobile-dbcache
        image: redis:alpine
        resources: {}
        ports:
        - containerPort: 6379
